CREATE TABLE DM1_KREDI_RAPOR (
    RAPOR_ID INT PRIMARY KEY,
    MUSTERI_ID INT,
    TOPLAM_KREDI_TUTAR DECIMAL(18,2),
    AKTIF_KREDI_SAYISI INT,
    RAPOR_TARIHI DATE
);

CREATE TABLE DM2_SEGMENT_ANALIZ (
    SEGMENT_ID INT,
    TOPLAM_MUSTERI INT,
    ORT_KREDI_TUTAR DECIMAL(18,2),
    ANALIZ_TARIHI DATE
);