-- DATA WAREHOUSE LAYER

CREATE TABLE DWH_MUSTERI (
    MUSTERI_ID INT PRIMARY KEY,
    TC_KIMLIK_NO VARCHAR(11),
    AD_SOYAD VARCHAR(100),
    DOGUM_TARIHI DATE,
    MUSTERI_TIP_ID INT,
    AKTIF_FLAG INT
);

CREATE TABLE DWH_KREDI (
    KREDI_ID INT PRIMARY KEY,
    MUSTERI_ID INT,
    KREDI_TUTAR DECIMAL(18,2),
    KREDI_TIP_ID INT,
    VADE_AY INT,
    AKTIF_FLAG INT,
    FOREIGN KEY (MUSTERI_ID) REFERENCES DWH_MUSTERI(MUSTERI_ID)
);

CREATE TABLE DWH_ISLEM (
    ISLEM_ID INT PRIMARY KEY,
    MUSTERI_ID INT,
    KREDI_ID INT,
    ISLEM_TUTAR DECIMAL(18,2),
    ISLEM_TARIHI DATE,
    ISLEM_TIP VARCHAR(50),
    FOREIGN KEY (MUSTERI_ID) REFERENCES DWH_MUSTERI(MUSTERI_ID),
    FOREIGN KEY (KREDI_ID) REFERENCES DWH_KREDI(KREDI_ID)
);