-- SOURCE LAYER TABLES
-- Core banking sisteminden gelen ham veriler

CREATE TABLE SRC_MUSTERI (
    MUSTERI_ID INT,
    TC_KIMLIK_NO VARCHAR(11),
    AD VARCHAR(50),
    SOYAD VARCHAR(50),
    DOGUM_TARIHI DATE,
    MUSTERI_TIP INT,
    CREATED_DATE DATE
);

CREATE TABLE SRC_KREDI (
    KREDI_ID INT,
    MUSTERI_ID INT,
    KREDI_AMT DECIMAL(18,2),
    KREDI_TIP INT,
    VADE_AY INT,
    BASLANGIC_TARIHI DATE,
    BITIS_TARIHI DATE
);