-- STAGING LAYER
-- Temizleme ve dönüşüm yapılan katman

CREATE TABLE STG_MUSTERI (
    MUSTERI_ID INT,
    TC_KIMLIK_NO VARCHAR(11),
    AD_SOYAD VARCHAR(100),
    DOGUM_TARIHI DATE,
    MUSTERI_TIP_ID INT,
    LOAD_DATE DATE
);

CREATE TABLE STG_KREDI (
    KREDI_ID INT,
    MUSTERI_ID INT,
    KREDI_TUTAR DECIMAL(18,2),
    KREDI_TIP_ID INT,
    VADE_AY INT,
    LOAD_DATE DATE
);